services:
  fred-query:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
    - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]